export const MODEL_PAGE = 'admin/flowable/model/page'
export const MODEL_DETAIL = 'admin/flowable/model/detail'
export const MODEL_SAVE_CONTENT = 'admin/flowable/model/saveContent'
export const MODEL_DEPLOY = 'admin/flowable/model/deploy'
export const MODEL_DELETE = 'admin/flowable/model/delete'
export const MODEL_GET_DEFINITION_CONTENT = 'admin/flowable/model/getDefinitionContent'
export const MODEL_DEFINITION_PAGE = 'admin/flowable/model/definitionPage'
export const MODEL_FORM_OPTIONS = 'admin/flowable/model/formOptions'
export const MODEL_JAVA_DELEGATE_OPTIONS = 'admin/flowable/model/javaDelegateOptions'
export const MODEL_VAR_LIST = 'admin/flowable/model/varList'
export const MODEL_ASSIGNEE_OPTIONS = 'admin/flowable/model/assigneeOptions'
export const MODEL_CANDIDATE_GROUPS_OPTIONS = 'admin/flowable/model/candidateGroupsOptions'
export const MODEL_CANDIDATE_USERS_OPTIONS = 'admin/flowable/model/candidateUsersOptions'

export const SIMULATE_GET = 'admin/flowable/simulate/get'
export const SIMULATE_USERS = 'admin/flowable/simulate/users'
export const SIMULATE_LIST = 'admin/flowable/simulate/list'
export const SIMULATE_START = 'admin/flowable/simulate/start'
export const SIMULATE_STATUS = 'admin/flowable/simulate/status'
export const SIMULATE_TASK_HANDLE = 'admin/flowable/simulate/task/handle'
export const SIMULATE_DELETE = 'admin/flowable/simulate/delete'

export const USER_TASK_TODO_PAGE = 'admin/flowable/user-task/todoTaskPage'
export const USER_TASK_DONE_PAGE = 'admin/flowable/user-task/doneTaskPage'
export const USER_TASK_MY_INSTANCE = 'admin/flowable/user-task/myInstance'
export const USER_TASK_GET_INSTANCE_INFO = 'admin/flowable/user-task/getInstanceInfo'
export const USER_TASK_GET_INSTANCE_INFO_BY_TASK_ID = 'admin/flowable/user-task/getInstanceInfoByTaskId'
export const USER_TASK_HANDLE_TASK = 'admin/flowable/user-task/handleTask'

export const MONITOR_PROCESS_INSTANCE_CLOSE = 'admin/flowable/monitor/processInstance/close'
export const MONITOR_INSTANCE_PAGE = 'admin/flowable/monitor/instancePage'
export const MONITOR_SET_ASSIGNEE = 'admin/flowable/monitor/setAssignee'
export const MONITOR_TASK = 'admin/flowable/monitor/task'
export const MONITOR_DEFINITION_PAGE = 'admin/flowable/monitor/definitionPage'
export const MONITOR_INSTANCE_VARS = 'admin/flowable/monitor/instance/vars'

export const EXAMPLE_LEAVE_LIST = 'admin/flowable/example/leave/list'
export const EXAMPLE_LEAVE_DETAIL = 'admin/flowable/example/leave/detail'
export const EXAMPLE_LEAVE_START = 'admin/flowable/example/leave/start'
