## Flowable 工作流模块预设菜单
menus:
  myFlowableTask:
    name: 我的任务
    path: /flowable/user-task
    icon: ScheduleOutlined
    seq: -1
    refreshOnTabClick: true
    messageCountUrl: /admin/flowable/user-task/todoCount
    perms:
      - {name: 任务管理, code: myFlowableTask:manage}
  flowable:
    pid: sys
    name: 流程管理
    icon: GatewayOutlined
    path: /flowable
    seq: 10
    perms:
      - {name: 设计, code: flowableModel:design}
      - {name: 部署, code: flowableModel:deploy}
      - {name: 设置办理人, code: flowableTask:setAssignee}
      - {name: 终止流程, code: flowableInstance:close}
